Repository ut-issl/c2a-core, pull requests merged in 2021-11, with the labels that each got.

#31 Fix job name of workflow
  .github/workflows/build_as_c89.yml
  .github/workflows/build_as_cxx.yml
Labels: bug, priority::high, tools

#40 Readme の更新
  Docs/.gitkeep
  README.md
Labels: documentation, priority::low

#42 最低限のコード規約をチェックするお手製CIを追加
  .github/workflows/build_as_cxx.yml
  .github/workflows/check_coding_rule.yml
  Script/CI/check_coding_rule.json
  Script/CI/check_coding_rule.py
Labels: priority::medium, tools

#43 テストの追加
  .gitignore
  Examples/minimum_user_for_s2e/src/src_user/Test/README.md
  Examples/minimum_user_for_s2e/src/src_user/Test/authorization.json.temp
  Examples/minimum_user_for_s2e/src/src_user/Test/pytest.ini
  Examples/minimum_user_for_s2e/src/src_user/Test/settings.json
  Examples/minimum_user_for_s2e/src/src_user/Test/test/conftest.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/AnomalyLogger/test_anomaly_logger.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/ModeManager/test_mode_manager.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TaskManager/test_task_dispatcher.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_obc_time.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/WatchdogTimer/test_watchdog_timer.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_user/.gitkeep
  Examples/minimum_user_for_s2e/src/src_user/Test/utils/c2a_enum_utils.py
  Examples/minimum_user_for_s2e/src/src_user/Test/utils/wings_utils.py
  README.md
Labels: priority::medium, tools

#37 [minimum_user] SILS用のラッパー部分のソースファイルを.cppにする
  Examples/minimum_user_for_s2e/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/IfWrapper/Sils/ccsds_sils.cpp
  Examples/minimum_user_for_s2e/src/src_user/IfWrapper/Sils/ccsds_sils_sci_if.cpp
  Examples/minimum_user_for_s2e/src/src_user/IfWrapper/Sils/ccsds_sils_sci_if.hpp
  Examples/minimum_user_for_s2e/src/src_user/IfWrapper/Sils/uart_sils.cpp
  Examples/minimum_user_for_s2e/src/src_user/IfWrapper/Sils/uart_sils_sci_if.cpp
  Examples/minimum_user_for_s2e/src/src_user/IfWrapper/Sils/uart_sils_sci_if.hpp
  Examples/minimum_user_for_s2e/src/src_user/IfWrapper/Sils/wdt_sils.cpp
Labels: enhancement, priority::high

#58 Event Handler の新規実装
  Applications/event_utility.c
  Applications/event_utility.h
  Applications/timeline_command_dispatcher.c
  Examples/minimum_user_for_s2e/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/NormalBlockCommandDefinition/nbc_header.h
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/NormalBlockCommandDefinition/nbc_respond_eh_for_test.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/block_command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/block_command_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/command_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/command_source.h
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/telemetry_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/telemetry_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/telemetry_source.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_BCT.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_INDEX.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_LOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_RULE.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH_INDEX.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH_LOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH_RULE.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/EventHandlerRules/event_handler_rule_test.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/EventHandlerRules/event_handler_rules.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/EventHandlerRules/event_handler_rules.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/event_handler_params.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/event_logger_group.h
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/Applications/test_event_utility.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py
  System/EventManager/event_handler.c
  System/EventManager/event_handler.h
  System/EventManager/event_logger.c
  System/EventManager/event_logger.h
  System/EventManager/event_manager.c
  System/EventManager/event_manager.h
  System/TaskManager/task_dispatcher.c
  System/TimeManager/obc_time.c
  System/TimeManager/obc_time.h
Labels: enhancement, priority::high

#66 Doxyfileをいれて，Referenceを自動生成させる
  Examples/minimum_user_for_s2e/Doxyfile
Labels: documentation, enhancement, priority::medium
