Repository ut-issl/c2a-core, pull requests merged in 2021-12, with the labels that each got.

#67 S2E mockup
  .github/workflows/build_as_cxx.yml
  Examples/minimum_user_for_s2e/src/s2e_mockup/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/s2e_mockup/CMakeSettings.json
  Examples/minimum_user_for_s2e/src/s2e_mockup/main.cpp
Labels: priority::medium

#68 Add WINGS, S2E label
  .github/labels.yml
Labels: tools

#74 GS で Warningが出ていたので修正
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Com/gs.c
Labels: priority::low

#76 ドキュメントの追加
  Docs/.gitkeep
  Docs/Application/Overview.md
  Docs/Core/Tips.md
  Docs/Driver/Overview.md
  Docs/General/CodingRule.md
  Docs/General/Overview.md
  Docs/README.md
  Docs/Tips/ParameterSettings.md
  Docs/Tools/Overview.md
Labels: documentation, priority::medium

#72 CAとTFの軽いリファクタ
  Applications/telemetry_manager.c
  CmdTlm/block_command_table.c
  CmdTlm/command_analyze.c
  CmdTlm/command_analyze.h
  CmdTlm/telemetry_frame.c
  CmdTlm/telemetry_frame.h
  CmdTlm/telemetry_generator.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/telemetry_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_CA.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TF.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_CA.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_TF.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/command_analyze_params.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/telemetry_frame_params.h
Labels: priority::high, tools

#73 WextraのWarningを消す
  Drivers/Super/driver_super.c
  Drivers/Super/driver_super.h
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/block_command_user_settings.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/user_packet_handler.c
  System/ApplicationManager/app_manager.h
  System/EventManager/event_handler.h
  System/EventManager/event_logger.h
  System/TaskManager/task_dispatcher.c
Labels: priority::medium

#60 初期化中の get clock の動作変更
  Examples/minimum_user_for_s2e/src/src_user/c2a_main.c
  System/ApplicationManager/app_manager.c
  System/TimeManager/obc_time.c
  System/TimeManager/obc_time.h
  System/TimeManager/time_manager.c
  System/TimeManager/time_manager.h
  c2a_core_main.c
Labels: priority::medium

#81 HKにダミーバイトを追加
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/telemetry_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
Labels: priority::low

#78 Docs内部のリンクを修正
  Docs/General/Overview.md
Labels: documentation, priority::low

#35 CMakeLists.txtのリファクタリング
  Applications/CMakeLists.txt
  CMakeLists.txt
  Docs/README.md
  Docs/Sils/S2eIntegration.md
  Examples/minimum_user_for_s2e/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/s2e_mockup/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/Applications/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/Drivers/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/IfWrapper/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/Library/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/Settings/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/common.cmake
  Library/CMakeLists.txt
  common.cmake
Labels: enhancement, priority::medium, tools, S2E

#83 Fix CMakeLists.txt for Printf
  Examples/minimum_user_for_s2e/CMakeLists.txt
  Library/CMakeLists.txt
Labels: bug, priority::high

#77 ELの軽微な性能改善
  System/EventManager/event_logger.c
Labels: priority::medium

#88 ISSL MOBCのマイコンIDEでのWarningを消す
  CmdTlm/packet_list.c
  Drivers/Super/driver_super.c
Labels: bug, priority::high

#85 リンク関係のCMakeの修正
  .github/workflows/build_as_c89.yml
  Applications/CMakeLists.txt
  CMakeLists.txt
  Examples/minimum_user_for_s2e/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/Applications/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/Drivers/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/IfWrapper/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/Library/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/Library/print.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/CMakeLists.txt
  Library/CMakeLists.txt
  common.cmake
Labels: priority::medium, tools

#70 コマンドのパラメタ取得の定型化
  Applications/divided_cmd_utility.c
  Applications/telemetry_manager.c
  CmdTlm/block_command_table.c
  CmdTlm/command_analyze.c
  CmdTlm/command_analyze.h
  CmdTlm/common_tlm_cmd_packet_util.c
  CmdTlm/common_tlm_cmd_packet_util.h
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/command_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/telemetry_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/Library/stdint.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_CA.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_CA.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/command_analyze_params.h
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/CmdTlm/test_command_analyze.py
  System/EventManager/event_logger.c
Labels: enhancement, priority::medium

#95 Delete anonymous union
  CmdTlm/command_analyze.c
  CmdTlm/command_analyze.h
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/telemetry_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_CA.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_CA.csv
Labels: bug, priority::high

#99 Fix check_coding_rule CI
  .github/workflows/check_coding_rule.yml
  Script/CI/check_coding_rule.json
  Script/CI/check_coding_rule.py
Labels: bug, priority::high, tools

#101 C89ビルドのworkflowをまとめる
  .github/workflows/build_as_c89.yml
  .github/workflows/build_as_c89_wextra.yml
Labels: tools

#100 WDT_init を C2A_init_ に追加
  Examples/minimum_user_for_s2e/src/src_user/c2a_main.c
Labels: priority::low

#75 Update pre-commit hook
  Script/Git/pre-commit
  setup.bat
  setup.sh
Labels: bug, priority::low, tools

#102 C89規格に準拠したワーニングを出す
  .github/workflows/build_as_c89.yml
  .github/workflows/build_as_cxx.yml
  Examples/minimum_user_for_s2e/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/c2a_main.c
  common.cmake
Labels: tools

#104 Delete old unused core lib
  .github/workflows/build_as_c89.yml
  .github/workflows/build_as_cxx.yml
  Library/CMakeLists.txt
  Library/exor.c
  Library/exor.h
  Library/matrix.c
  Library/matrix.h
  Library/quaternion.c
  Library/quaternion.h
  Library/sum.c
  Library/sum.h
  Library/vector.c
  Library/vector.h
Labels: priority::high

#105 C89に準拠させる
  Applications/divided_cmd_utility.h
  Applications/telemetry_manager.h
  Examples/minimum_user_for_s2e/src/src_user/Applications/app_registry.h
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/block_command_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/Applications/AnomalyHandlerRules/ah_rules.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/EventHandlerRules/event_handler_rules.h
  IfWrapper/uart.h
  Library/majority_vote_for3.h
  System/EventManager/event_handler.c
  System/EventManager/event_logger.c
  System/EventManager/event_logger.h
Labels: priority::high

#108 C89のWallででるWarningをすべて消す
  CmdTlm/telemetry_frame.c
  Examples/minimum_user_for_s2e/src/src_user/Applications/UserDefined/debug_apps.c
Labels: bug, priority::medium

#98 Cmd_BCT_OVERWRITE_CMD を可変長 Cmd に対応
  CmdTlm/block_command_table.c
Labels: bug, priority::low

#107 諸々のCIをdevelop,mainへのpushでも走らせる
  .github/workflows/build_as_c89.yml
  .github/workflows/build_as_cxx.yml
  .github/workflows/check_coding_rule.yml
  .github/workflows/check_encoding.yml
Labels: priority::medium, tools

#109 clang-tidyでreviewdogにビルドCIのerror,warningを出させる
  .github/workflows/build_as_c89.yml
Labels: priority::low, tools

#115 Warning 消し
  CmdTlm/command_analyze.c
  CmdTlm/common_tlm_cmd_packet_util.c
Labels: priority::low

#120 Disable reviewdog clang-tidy (github-check)
  .github/workflows/build_as_c89.yml
Labels: bug, tools

#110 S2E mockupの更新
  Examples/minimum_user_for_s2e/src/s2e_mockup/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/s2e_mockup/main.cpp
Labels: priority::medium, S2E

#122 CAとCCP_formの安全性の向上
  CmdTlm/command_analyze.c
  CmdTlm/common_tlm_cmd_packet_util.c
  CmdTlm/common_tlm_cmd_packet_util.h
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py
  System/EventManager/event_logger.h
Labels: enhancement, priority::medium

#116 Cmd_TMGR_SET_UNIXTIMEの引数を整理 & unixtimeのリネーム
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/telemetry_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py
  System/TimeManager/obc_time.c
  System/TimeManager/obc_time.h
  System/TimeManager/time_manager.c
  System/TimeManager/time_manager.h
Labels: priority::medium

#130 ObcTimeとTMGRで関数の順番を変更
  System/TimeManager/obc_time.c
  System/TimeManager/obc_time.h
  System/TimeManager/time_manager.c
  System/TimeManager/time_manager.h
Labels: priority::high

#131 EL, EHのテストのenum周りを改善
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/NormalBlockCommandDefinition/nbc_respond_eh_for_test.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/EventHandlerRules/event_handler_rule_test.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/event_logger_group.h
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py
Labels: priority::medium, tools

#132 EHのコマンドパラメタ取得方法の更新
  System/EventManager/event_handler.c
Labels: priority::medium

#142 TlmDefで一時変数を使えるようにする
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/telemetry_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB.xlsm
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_AM.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_APP_TIME.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_BL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_CA.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_DCU.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_INDEX.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_LOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_RULE.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL_CLOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL_TLOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_GIT_REV.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MEM.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MM.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TF.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TLM_MGR.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_UART_TEST.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_AM.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_APP_TIME.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_BL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_CA.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_DCU.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH_INDEX.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH_LOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH_RULE.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EL_CLOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EL_TLOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_GIT_REV.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MEM.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MM.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_TF.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_TL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_TLM_MGR.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_UART_TEST.csv
Labels: enhancement, priority::high, tools

#134 EHでの二分探索をbsearchで書き直した
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py
  System/EventManager/event_handler.c
Labels: priority::medium

#150 NOPにdoxygenコメントを追加
  Applications/nop.c
  Applications/nop.h
Labels: documentation, priority::medium

#139 多段のEH対応の実装
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/command_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/telemetry_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_INDEX.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_LOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_RULE.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL_CLOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL_TLOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH_INDEX.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH_LOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH_RULE.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EL_CLOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EL_TLOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/EventHandlerRules/event_handler_rule_test.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/event_logger_params.h
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py
  System/EventManager/event_handler.c
  System/EventManager/event_handler.h
  System/EventManager/event_logger.c
  System/EventManager/event_logger.h
Labels: enhancement, priority::high

#143 EHのカウンタ周りの改善とアノマリが正常に戻ったときのUtilを追加
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/command_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py
  System/EventManager/event_handler.c
  System/EventManager/event_handler.h
Labels: enhancement, priority::high

#147 TFの変数の型を修正し，Wextraを消す
  CmdTlm/telemetry_frame.c
Labels: priority::medium

#148 AppInfoにdoxygenコメントを追加，コード規約に合わせるように修正
  Applications/anomaly_handler.c
  Applications/divided_cmd_utility.c
  Applications/event_utility.c
  Applications/gs_command_dispatcher.c
  Applications/memory_dump.c
  Applications/nop.c
  Applications/realtime_command_dispatcher.c
  Applications/telemetry_manager.c
  Applications/timeline_command_dispatcher.c
  Applications/utility_command.c
  Applications/utility_counter.c
  Docs/General/CodingRule.md
  Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_gs.c
  Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_uart_test.c
  Examples/minimum_user_for_s2e/src/src_user/Applications/UserDefined/debug_apps.c
  System/ApplicationManager/app_info.c
  System/ApplicationManager/app_info.h
  System/TaskManager/task_dispatcher.c
Labels: documentation, priority::medium

#149 GSCDにdoxygenコメントを追加
  Applications/gs_command_dispatcher.c
  Applications/gs_command_dispatcher.h
Labels: documentation, priority::medium
