Repository ut-issl/c2a-core, pull requests merged in 2022-04, with the labels that each got.

#268 GSCD，TLCD，RTCDなどの実行時エラー履歴を残す
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/TlmCmd/test_command_dispatcher.py
  System/EventManager/event_logger.h
  TlmCmd/command_dispatcher.c
Labels: enhancement, priority::medium

#309 コーディング規約チェックスクリプトに，ルール単位でのignoreを追加
  Script/CI/check_coding_rule.json
  Script/CI/check_coding_rule.py
Labels: priority::medium, tools

#310 コーディング規約スクリプトで，プリプロセッサの改行 `\` がエラーになる問題を修正
  Script/CI/check_coding_rule.py
Labels: priority::medium, tools

#311 Pre Release (v3.6.0-beta.1): Tlm DBのupdate
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB.xlsm
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_AM.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_APP_TIME.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_BL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_CA.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_DCU.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_INDEX.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_LOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_RULE.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL_CLOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL_TLOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_GIT_REV.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MEM.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MM.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TF.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TLM_MGR.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_UART_TEST.csv
  c2a_core_main.h
Labels: priority::medium, tools

#312 test_command_dispatcher 内の sleep の時間を変更
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/TlmCmd/test_command_dispatcher.py
Labels: priority::low

#307 TL0をバス用とミッション用の二つに分割する（やり直し）
  Applications/timeline_command_dispatcher.c
  Applications/timeline_command_dispatcher.h
  Examples/minimum_user_for_s2e/src/src_user/Applications/app_registry.c
  Examples/minimum_user_for_s2e/src/src_user/Applications/app_registry.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/Applications/timeline_command_dispatcher_define.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/TaskLists/Elements/tl_elem_tlm_cmd_hirate.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/packet_handler_params.h
  TlmCmd/Ccsds/cmd_space_packet.c
  TlmCmd/common_cmd_packet.h
  TlmCmd/packet_handler.c
  TlmCmd/packet_handler.h
Labels: priority::medium, WINGS

#314 Pre Release (v3.6.0-beta.2): TLCDのリファクタ
  Applications/anomaly_handler.c
  Applications/telemetry_manager.c
  Applications/timeline_command_dispatcher.c
  Applications/timeline_command_dispatcher.h
  Examples/minimum_user_for_s2e/src/src_user/Applications/app_registry.c
  Examples/minimum_user_for_s2e/src/src_user/Applications/app_registry.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/TaskLists/Elements/tl_elem_tlm_cmd_hirate.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/TaskLists/tl_initial.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/Transitions/sequence_items.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/Transitions/sequence_items.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/Transitions/sl_initial.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_TL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/packet_handler_params.h
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_start_hk_tlm.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/telemetry_definitions.c
  System/EventManager/event_handler.c
  System/ModeManager/mode_manager.c
  TlmCmd/Ccsds/cmd_space_packet.c
  TlmCmd/block_command_loader.c
  TlmCmd/block_command_loader.h
  TlmCmd/common_cmd_packet.h
  TlmCmd/common_cmd_packet_util.c
  TlmCmd/common_cmd_packet_util.h
  TlmCmd/packet_handler.c
  TlmCmd/packet_handler.h
  TlmCmd/packet_list.c
  c2a_core_main.h
Labels: priority::low

#322 コメントスタイルの微修正
  Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_aobc.c
  Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_aobc.h
  Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_uart_test.c
  Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_uart_test.h
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc.c
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc.h
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Etc/UART_TEST.c
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Etc/UART_TEST.h
  Examples/minimum_user_for_s2e/src/src_user/IfWrapper/Sils/ccsds_sils.cpp
Labels: priority::medium

#316 Pre Release (v3.6.0-beta.3): TLCDのpytestを追加
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/Applications/test_timeline_command_dispatcher.py
  c2a_core_main.h
Labels: priority::medium

#320 CCP register cmd 関数の追加
  TlmCmd/common_cmd_packet_util.c
  TlmCmd/common_cmd_packet_util.h
Labels: enhancement, priority::medium
