Repository ut-issl/c2a-core, pull requests merged in 2022-09, with the labels that each got.

#418 コマンド返り値が CCP_CmdRet に変わったことに付随する細かい改善
  Drivers/Super/driver_super.c
  System/TimeManager/time_manager.c
  TlmCmd/block_command_table.c
Labels: enhancement, priority::medium

#422 循環参照を防ぐために TLCD_ID の定義を外部ファイル化
  Applications/anomaly_handler.c
  Applications/timeline_command_dispatcher.h
  Applications/timeline_command_dispatcher_id_define.h
  Examples/2nd_obc_user/src/src_user/Settings/Modes/Transitions/sl_initial.c
  Examples/2nd_obc_user/src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_start_hk_tlm.c
  Examples/minimum_user/src/src_user/Settings/Modes/Transitions/sequence_items.h
  Examples/minimum_user/src/src_user/Settings/Modes/Transitions/sl_initial.c
  Examples/minimum_user/src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_start_hk_tlm.c
  System/EventManager/event_handler.c
  System/ModeManager/mode_manager.c
  TlmCmd/block_command_loader.c
  TlmCmd/block_command_loader.h
  TlmCmd/common_cmd_packet_util.h
  TlmCmd/packet_handler.h
Labels: enhancement, priority::high

#424 SPI_CS_STATE_AFTER_TXの値変更
  IfWrapper/spi.h
Labels: priority::high

#421 Cmd の返り値を CCP_EXEC_STS から CCP_CmdRet に（つづき）
  Examples/2nd_obc_user/src/src_user/Applications/UserDefined/debug_apps.c
  Examples/2nd_obc_user/src/src_user/TlmCmd/telemetry_definitions.c
  Examples/2nd_obc_user/src/src_user/TlmCmd/user_packet_handler.c
  Examples/2nd_obc_user/src/src_user/TlmCmd/user_packet_handler.h
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_aobc.c
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_aobc.h
  Examples/minimum_user/src/src_user/Applications/UserDefined/debug_apps.c
  Examples/minimum_user/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py
  Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_command_dispatcher.py
  Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.c
  Examples/minimum_user/src/src_user/TlmCmd/user_packet_handler.c
  Examples/minimum_user/src/src_user/TlmCmd/user_packet_handler.h
  System/EventManager/event_handler.c
  System/EventManager/event_logger.h
  System/TaskManager/task_dispatcher.c
  System/TaskManager/task_dispatcher.h
  TlmCmd/block_command_executor.c
  TlmCmd/command_analyze.c
  TlmCmd/command_analyze.h
  TlmCmd/command_dispatcher.c
  TlmCmd/command_dispatcher.h
  TlmCmd/common_cmd_packet.h
  TlmCmd/common_cmd_packet_util.c
  TlmCmd/common_cmd_packet_util.h
  TlmCmd/packet_handler.c
  TlmCmd/packet_handler.h
Labels: enhancement, priority::medium

#426 Pre Release (v3.8.0-beta.0): Cmd 返り値修正にともなる Tlm の整理
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/2nd_obc_user/src/src_user/Test/test/test_comm_between_c2a.py
  Examples/2nd_obc_user/src/src_user/TlmCmd/telemetry_definitions.c
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc_telemetry_buffer.c
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc_telemetry_data_definitions.h
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user/src/src_user/Test/test/src_core/Applications/test_timeline_command_dispatcher.py
  Examples/minimum_user/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py
  Examples/minimum_user/src/src_user/Test/test/src_core/System/ModeManager/test_mode_manager.py
  Examples/minimum_user/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py
  Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_command_dispatcher.py
  Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.c
  c2a_core_main.h
Labels: priority::medium

#428 TDSP の微修正
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/2nd_obc_user/src/src_user/TlmCmd/telemetry_definitions.c
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.c
  System/TaskManager/task_dispatcher.c
  System/TaskManager/task_dispatcher.h
Labels: priority::medium

#432 is ccsds tx valid を削除
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_gs.c
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_gs.h
  Examples/minimum_user/src/src_user/Drivers/Com/gs.c
  Examples/minimum_user/src/src_user/Drivers/Com/gs.h
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user/src/src_user/TlmCmd/command_definitions.c
  Examples/minimum_user/src/src_user/TlmCmd/command_definitions.h
  Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.c
Labels: priority::low

#433 vcdu replay flag を追加
  Examples/minimum_user/src/src_user/TlmCmd/Ccsds/vcdu.c
Labels: bug, priority::low

#437 fix include bug
  Applications/timeline_command_dispatcher.c
Labels: bug, priority::high

#441 DS のメンバを整理する（設定値なのか取得値なのか内部メンバなのかの明示）
  Drivers/Super/driver_super.c
  Drivers/Super/driver_super.h
  Examples/minimum_user/src/src_user/Drivers/Com/gs.c
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_UART_TEST.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_UART_TEST.csv
  Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.c
Labels: enhancement, priority::high

#447 GS Driver の enum の命名を修正 (やり直し)
  Examples/minimum_user/src/src_user/Drivers/Com/gs.c
Labels: priority::high
