Repository ut-issl/c2a-core, pull requests merged in 2022-07, with the labels that each got.

#373 Fix set -rdynamic on link time only
  common.cmake
Labels: priority::low, tools

#377 Add ArkEdgeSpace logo to readme
  Docs/Img/arkedgespace_logo.png
  README.md
Labels: priority::medium

#387 SCIDのデフォルト値を修正
  Examples/minimum_user/src/src_user/TlmCmd/Ccsds/tc_transfer_frame.h
Labels: priority::high, WINGS
