Repository ut-issl/c2a-core, pull requests merged in 2022-02, with the labels that each got.

#226 Pre Release (v3.5.0-beta.2): Space Packet標準化にともなうC2A間通信の対応
  Drivers/Super/driver_super_issl_format.c
  Drivers/Super/driver_super_issl_format.h
  Examples/minimum_user_for_s2e/src/src_user/Applications/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_aobc.c
  Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_aobc.h
  Examples/minimum_user_for_s2e/src/src_user/Applications/app_headers.h
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc.c
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc.h
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc_command_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc_telemetry_buffer.c
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc_telemetry_buffer.h
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc_telemetry_data_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc_telemetry_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/Drivers/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/CMDFILE/.gitkeep
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/CMD_DB/SAMPLE_AOBC_CMD_DB.xlsm
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/CMD_DB/SAMPLE_AOBC_CMD_DB_BCT.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/CMD_DB/SAMPLE_AOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/CMD_DB/SAMPLE_AOBC_CMD_DB_Utility.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/README.md
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/SAMPLE_AOBC_TLM_DB.xlsm
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/calced_data/.gitkeep
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/port_config.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/common_tlm_packet.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/telemetry_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/telemetry_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/telemetry_source.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/user_packet_handler.c
  TlmCmd/Ccsds/tlm_space_packet.c
  TlmCmd/Ccsds/tlm_space_packet.h
  TlmCmd/common_tlm_packet.h
  TlmCmd/telemetry_frame.c
  TlmCmd/telemetry_frame.h
  TlmCmd/telemetry_generator.c
  c2a_core_main.h
Labels: enhancement, priority::high

#228 Update release.md
  Docs/General/release.md
Labels: documentation, priority::low

#230 Unify indentation with spaces in Docs
  Docs/Application/overview.md
  Docs/Core/tips.md
  Docs/General/coding_rule.md
  Docs/General/release.md
  Docs/README.md
Labels: documentation, priority::medium

#229 パケットの記述をドキュメントに追加
  Docs/Core/communication.md
Labels: documentation, priority::low

#232 CTCP分離とSpacePacket実装に伴う，PHの微修正とPLのコメント修正
  TlmCmd/packet_handler.c
  TlmCmd/packet_handler.h
  TlmCmd/packet_list.c
  TlmCmd/packet_list.h
Labels: priority::medium

#236 Change git hooks script directory
  Script/GitHooks/pre-commit
  setup.bat
  setup.sh
Labels: priority::medium, tools

#235 Fix check_coding_rule workflow
  .github/workflows/check_coding_rule.yml
  Script/CI/check_coding_rule.json
Labels: bug, priority::high, tools

#238 CTP, CCP, CTCPのincludeで不適切なものを直す
  Applications/anomaly_handler.h
  Applications/divided_cmd_utility.h
  Applications/event_utility.h
  Applications/memory_dump.h
  Applications/nop.h
  Applications/realtime_command_dispatcher.h
  Applications/telemetry_manager.h
  Applications/timeline_command_dispatcher.h
  Applications/utility_command.h
  Applications/utility_counter.h
  Drivers/Super/driver_super_issl_format.h
  Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_aobc.h
  Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_uart_test.h
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc.c
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc.h
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Etc/UART_TEST.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/Transitions/SequenceItems.h
  System/AnomalyLogger/anomaly_logger.h
  System/ApplicationManager/app_manager.h
  System/EventManager/event_logger.h
  System/ModeManager/mode_manager.h
  System/TimeManager/time_manager.h
  System/WatchdogTimer/watchdog_timer.h
  TlmCmd/block_command_executor.h
  TlmCmd/block_command_table.h
  TlmCmd/command_analyze.h
  TlmCmd/command_dispatcher.h
  TlmCmd/packet_list.c
  TlmCmd/packet_list.h
  TlmCmd/packet_list_util.h
  TlmCmd/telemetry_frame.h
  TlmCmd/telemetry_generator.h
Labels: priority::medium

#234 インクルードガードのチェックを有効に
  Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_uart_test.h
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Etc/UART_TEST.h
  Examples/minimum_user_for_s2e/src/src_user/IfWrapper/Sils/ccsds_sils_sci_if.hpp
  Examples/minimum_user_for_s2e/src/src_user/IfWrapper/Sils/uart_sils_sci_if.hpp
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/TaskLists/InitialTL.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/Transitions/InitialSL.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/Transitions/NopSL.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/Transitions/SequenceItems.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/mode_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/AppManagerParams.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/initial_settings.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/Ccsds/TCFrame.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/Ccsds/TCSegment.h
  Library/ascii_conv.h
  Library/endian_conv.h
  Library/majority_vote_for3.h
  Library/print.h
  Script/CI/check_coding_rule.json
  Script/CI/check_coding_rule.py
Labels: priority::medium, tools

#240 Driver Super の doxygen コメントの修正
  Drivers/Super/driver_super.c
  Drivers/Super/driver_super.h
Labels: priority::low

#239 EHでの多段対応の上限を追加（無限ループ回避），ドキュメント整備
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/event_handler_params.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH.csv
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/telemetry_definitions.c
  System/EventManager/event_handler.c
  System/EventManager/event_handler.h
Labels: documentation, priority::medium

#241 Update version (v3.5.0)
  c2a_core_main.h
Labels: priority::medium

#244 Revert "Update version (v3.5.0)"
  c2a_core_main.h
Labels: bug, priority::medium

#245 Fix Build CI exit value
  .github/workflows/build_as_c89.yml
  Applications/memory_dump.c
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc.h
  TlmCmd/Ccsds/cmd_space_packet.h
  TlmCmd/Ccsds/tlm_space_packet.h
  TlmCmd/packet_list.h
Labels: bug, priority::high, tools

#246 Update version (v3.5.0): やり直し
  c2a_core_main.h
Labels: priority::medium

#248 mdのインデントを2 spaceから4 spaceにする
  Docs/Application/overview.md
  Docs/Core/communication.md
  Docs/Core/tips.md
  Docs/Driver/overview.md
  Docs/General/coding_rule.md
  Docs/General/release.md
  Docs/README.md
  Docs/Tips/parameter_settings.md
  Examples/minimum_user_for_s2e/src/src_user/IfWrapper/SilsMockup/README.md
  Examples/minimum_user_for_s2e/src/src_user/Test/README.md
Labels: documentation, priority::low

#242 PH の返り値について整理
  Applications/divided_cmd_utility.c
  Applications/timeline_command_dispatcher.c
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Com/gs.c
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Com/gs.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/telemetry_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/user_packet_handler.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/user_packet_handler.h
  TlmCmd/packet_handler.c
  TlmCmd/packet_handler.h
Labels: good first issue, priority::medium

#257 SILSなどの記載をreadmeに追加
  Examples/minimum_user_for_s2e/README.md
  README.md
Labels: documentation, priority::high

#258 S2Eと一緒にビルドするCIを入れる
  .github/workflows/build_with_s2e.yml
Labels: enhancement, priority::medium, tools, S2E

#261 CDIS などの修正
  System/EventManager/event_logger.h
  TlmCmd/command_dispatcher.c
  TlmCmd/command_dispatcher.h
  TlmCmd/packet_list.c
  TlmCmd/packet_list.h
Labels: priority::medium
