Repository ut-issl/c2a-core, pull requests merged in 2022-08, with the labels that each got.

#388 ドキュメントの微修正
  Docs/General/coding_rule.md
Labels: documentation, priority::high

#386 Pre Release (v3.7.0-beta.0): C2A間通信のテストを追加
  Docs/Core/communication.md
  Examples/2nd_obc_user/src/src_user/Applications/UserDefined/debug_apps.c
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/CMDFILE/.gitkeep
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/CMDFILE/sample.ops
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_AOBC_CMD_DB_CMD_DB.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/2nd_obc_user/src/src_user/Test/.gitkeep
  Examples/2nd_obc_user/src/src_user/Test/README.md
  Examples/2nd_obc_user/src/src_user/Test/authorization.json.temp
  Examples/2nd_obc_user/src/src_user/Test/pytest.ini
  Examples/2nd_obc_user/src/src_user/Test/settings.json
  Examples/2nd_obc_user/src/src_user/Test/test/conftest.py
  Examples/2nd_obc_user/src/src_user/Test/test/test_comm_between_c2a.py
  Examples/2nd_obc_user/src/src_user/Test/utils/c2a_enum_utils.py
  Examples/2nd_obc_user/src/src_user/Test/utils/wings_utils.py
  Examples/2nd_obc_user/src/src_user/TlmCmd/telemetry_definitions.c
  Examples/2nd_obc_user/sync_with_minimum_user.bat
  Examples/minimum_user/src/src_user/Applications/app_registry.c
  Examples/minimum_user/src/src_user/Applications/app_registry.h
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc_telemetry_buffer.c
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc_telemetry_buffer.h
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc_telemetry_data_definitions.h
  Examples/minimum_user/src/src_user/IfWrapper/Sils/uart_sils.cpp
  Examples/minimum_user/src/src_user/Settings/Modes/TaskLists/Elements/tl_elem_drivers_update.c
  Examples/minimum_user/src/src_user/Settings/Modes/TaskLists/tl_initial.c
  Examples/minimum_user/src/src_user/Settings/port_config.h
  Examples/minimum_user/src/src_user/Test/README.md
  c2a_core_main.h
Labels: documentation, enhancement, priority::high, tools

#398 Examples/2nd_obc_user と Examples/minimum_user の同期スクリプトの微修正
  Examples/2nd_obc_user/sync_with_minimum_user.bat
Labels: priority::high

#399 README のリンク修正
  README.md
Labels: documentation, priority::low

#391 Pre Release (v3.7.0-beta.1): EB90 frame, E90 packet の整備
  CMakeLists.txt
  Drivers/Protocol/common_tlm_cmd_packet_for_driver_super.c
  Drivers/Protocol/common_tlm_cmd_packet_for_driver_super.h
  Drivers/Protocol/data_link_layer_definition.h
  Drivers/Protocol/eb90_frame_for_driver_super.c
  Drivers/Protocol/eb90_frame_for_driver_super.h
  Drivers/Protocol/eb90_packet_for_driver_super.c
  Drivers/Protocol/eb90_packet_for_driver_super.h
  Drivers/Super/driver_super.h
  Drivers/Super/driver_super_issl_format.c
  Drivers/Super/driver_super_issl_format.h
  Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.c
  Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.h
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.h
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc_telemetry_buffer.c
  c2a_core_main.h
Labels: priority::high

#401 Driver 関数の返り値の型の修正などの軽微な修正
  Docs/Driver/overview.md
  Examples/2nd_obc_user/src/src_user/Applications/DriverInstances/di_mobc.c
  Examples/2nd_obc_user/src/src_user/Applications/DriverInstances/di_mobc.h
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_uart_test.c
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_uart_test.h
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.h
  Examples/minimum_user/src/src_user/Drivers/CMakeLists.txt
  Examples/minimum_user/src/src_user/Drivers/Com/gs.c
  Examples/minimum_user/src/src_user/Drivers/Com/gs.h
  Examples/minimum_user/src/src_user/Drivers/Etc/uart_test.c
  Examples/minimum_user/src/src_user/Drivers/Etc/uart_test.h
  Examples/minimum_user/src/src_user/IfWrapper/Sils/ccsds_sils.cpp
Labels: priority::high

#402 CRCライブラリの軽微な修正
  Drivers/Protocol/eb90_frame_for_driver_super.c
  Examples/minimum_user/src/src_user/TlmCmd/Ccsds/tc_transfer_frame.c
  Library/crc.c
  Library/crc.h
Labels: priority::medium

#403 C2A標準CRCを CRC-16-IBM から CRC-16-CCITT に変える
  Drivers/Protocol/eb90_frame_for_driver_super.c
  Drivers/Protocol/eb90_frame_for_driver_super.h
Labels: enhancement, priority::high

#404 Pre Release (v3.7.0-beta.2): C2A間通信の実装例に CRC のチェックを入れ，テストを通す
  Drivers/Protocol/eb90_frame_for_driver_super.c
  Drivers/Protocol/eb90_frame_for_driver_super.h
  Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.c
  Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.h
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.h
  c2a_core_main.h
Labels: enhancement, priority::high

#407 Pre Release (v3.7.0-beta.3): DB の UTF-8 化
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_AOBC_CMD_DB.xlsm
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_AOBC_CMD_DB_BCT.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_AOBC_CMD_DB_CMD_DB.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_AOBC_CMD_DB_Utility.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_AOBC_TLM_DB.xlsm
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB.xlsm
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_BCT.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_Utility.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB.xlsm
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_AM.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_APP_TIME.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_BL.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_CA.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_DCU.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_INDEX.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_LOG.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_RULE.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL_CLOG.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL_TLOG.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_GIT_REV.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MEM.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MM.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TF.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TL.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TLM_MGR.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_UART_TEST.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_AM.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_APP_TIME.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_BL.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_CA.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_DCU.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH_INDEX.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH_LOG.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH_RULE.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EL.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EL_CLOG.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EL_TLOG.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_GIT_REV.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MEM.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MM.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_TF.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_TL.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_TLM_MGR.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_UART_TEST.csv
  c2a_core_main.h
Labels: enhancement, priority::high, tools

#406 C2A間通信など， CTCP on EB90 frame のコンポ間通信の Driver を書きやすくする Util を整備
  Drivers/Protocol/common_tlm_cmd_packet_for_driver_super.c
  Drivers/Protocol/common_tlm_cmd_packet_for_driver_super.h
  Drivers/Protocol/eb90_packet_for_driver_super.h
  Drivers/Super/driver_super.c
  Drivers/Super/driver_super.h
  Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.c
  Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.h
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c
Labels: priority::medium

#408 コンポ間通信や frame についてのドキュメントを追加
  Docs/Core/communication.md
  Docs/Driver/communication_with_components.md
  Docs/Driver/overview.md
  Docs/README.md
  Examples/2nd_obc_user/README.md
Labels: documentation, priority::medium

#412 Merge Build CI workflow by matrix
  .github/workflows/build_as_c89.yml
  .github/workflows/build_as_c89_for_2nd_obc.yml
  .github/workflows/build_as_cxx.yml
  .github/workflows/build_as_cxx_for_2nd_obc.yml
  .github/workflows/build_with_s2e.yml
  .github/workflows/build_with_s2e_for_2nd_obc.yml
  .github/workflows/check_coding_rule.yml
  .github/workflows/check_coding_rule_for_2nd_obc.yml
Labels: priority::high, tools

#413 リリースドキュメントに微修正
  Docs/General/release.md
Labels: documentation, priority::high

#414 Update version (v3.7.0)
  c2a_core_main.h
Labels: priority::high
