Repository ut-issl/c2a-core, pull requests merged in 2022-11, with the labels that each got.

#448 DriverSuper のバッファサイズを可変にする
  Drivers/Super/driver_super.c
  Drivers/Super/driver_super.h
  Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.c
  Examples/2nd_obc_user/src/src_user/Settings/DriverSuper/driver_buffer_define.h
  Examples/2nd_obc_user/sync_with_minimum_user.bat
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c
  Examples/minimum_user/src/src_user/Drivers/Com/gs.c
  Examples/minimum_user/src/src_user/Drivers/Etc/uart_test.c
  Examples/minimum_user/src/src_user/Settings/DriverSuper/driver_buffer_define.h
  Examples/minimum_user/src/src_user/Settings/DriverSuper/driver_super_params.h
Labels: enhancement, priority::high

#453 DriverSuper のバッファ効率と速度向上のためのリファクタ
  Drivers/Super/driver_super.c
  Drivers/Super/driver_super.h
  Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.c
  Examples/2nd_obc_user/src/src_user/Settings/DriverSuper/driver_buffer_define.h
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c
  Examples/minimum_user/src/src_user/Drivers/Com/gs.c
  Examples/minimum_user/src/src_user/Drivers/Etc/uart_test.c
  Examples/minimum_user/src/src_user/Settings/DriverSuper/driver_buffer_define.h
  Examples/minimum_user/src/src_user/Settings/DriverSuper/driver_super_params.h
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_UART_TEST.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_UART_TEST.csv
  Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.c
Labels: enhancement, priority::high

#466 Driver Super での rx frame 取得関数でいかなる場合でも NULL が返らないようにする
  Drivers/Super/driver_super.c
  Drivers/Super/driver_super.h
Labels: priority::medium

#465 README の 採用実績・動作実績 の更新
  README.md
Labels: documentation, priority::medium

#451 Task List での GS 受信, 実行の頻度を増加
  Examples/minimum_user/src/src_user/Settings/Modes/TaskLists/tl_initial.c
Labels: priority::low

#470 Pre Release (v3.8.0-beta.2): Release ルールの更新と Core の機能更新の累積に伴う update (Driver Super, I2C)
  Docs/General/release.md
  c2a_core_main.h
Labels: documentation, priority::high

#472 Update README.md
  README.md
Labels: documentation, priority::medium
