Repository ut-issl/c2a-core, pull requests merged in 2022-06, with the labels that each got.

#339 Fix/Add CMake build options for user
  CMakeLists.txt
  Examples/minimum_user_for_s2e/CMakeLists.txt
  common.cmake
Labels: priority::high

#321 CCP UTIL TL の改善
  Examples/minimum_user_for_s2e/src/src_user/Applications/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/Applications/UserDefined/TestApp/test_ccp_util.c
  Examples/minimum_user_for_s2e/src/src_user/Applications/UserDefined/TestApp/test_ccp_util.h
  Examples/minimum_user_for_s2e/src/src_user/Applications/app_headers.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/TlmCmd/test_common_cmd_packet_util.py
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.h
  TlmCmd/common_cmd_packet_util.c
  TlmCmd/common_cmd_packet_util.h
  TlmCmd/packet_handler.c
  TlmCmd/packet_handler.h
Labels: enhancement, priority::medium

#344 workflowでのpythonバージョン指定の統一
  .github/workflows/.python-version
  .github/workflows/check_coding_rule.yml
  .github/workflows/check_encoding.yml
  .github/workflows/python_lint.yml
Labels: priority::low

#347 workflowでのpythonバージョンを固定
  .github/workflows/.python-version
Labels: priority::medium

#351 CCP_DEST_TYPE の説明を追記
  Docs/Core/communication.md
Labels: documentation, priority::high

#348 コマンドファイルのサンプルを追加
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/CMDFILE/.gitkeep
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/CMDFILE/sample.ops
Labels: documentation

#352 コーディング規約チェックスクリプトで，エラーがでないものがあったことの修正
  Script/CI/check_coding_rule.py
Labels: bug, priority::medium

#349 CCP UTIL と BCL で sub OBC のコマンドに対応
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/TlmCmd/test_block_command_loader.py
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_test_bcl.c
  TlmCmd/block_command_loader.c
  TlmCmd/block_command_loader.h
  TlmCmd/common_cmd_packet_util.c
  TlmCmd/common_cmd_packet_util.h
Labels: priority::high

#353 APIDのバリデーションをuser部に移動し， GENERATE_TLM で 2nd OBC の TI, Sequence counter を保存するようにした
  Examples/minimum_user/src/src_user/Settings/CMakeLists.txt
  Examples/minimum_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.c
  Examples/minimum_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.h
  Examples/minimum_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.h
  Examples/minimum_user/src/src_user/Settings/TlmCmd/common_tlm_packet_define.h
  TlmCmd/Ccsds/space_packet.c
  TlmCmd/common_tlm_cmd_packet.h
  TlmCmd/common_tlm_packet.h
  TlmCmd/telemetry_generator.c
Labels: enhancement, priority::high

#354 CCP_DEST_TYPE のバリデーションをuser部に移動
  Examples/minimum_user/src/src_user/Settings/CMakeLists.txt
  Examples/minimum_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.c
  Examples/minimum_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.h
  TlmCmd/Ccsds/cmd_space_packet.c
  TlmCmd/Ccsds/space_packet_typedef.h
Labels: bug, priority::high

#364 即時実行する CCP 作成関数の追加
  Applications/anomaly_handler.c
  System/EventManager/event_handler.c
  System/ModeManager/mode_manager.c
  TlmCmd/common_cmd_packet.h
  TlmCmd/common_cmd_packet_util.c
  TlmCmd/common_cmd_packet_util.h
Labels: enhancement, priority::high

#367 global time をユーザー定義に
  Examples/minimum_user/src/src_user/TlmCmd/common_tlm_packet.c
  TlmCmd/common_tlm_packet.h
  TlmCmd/telemetry_generator.c
Labels: priority::high

#365 CCP Util に raw パラメタコマンドの関数を追加
  Applications/TestApp/test_ccp_util.c
  Applications/TestApp/test_ccp_util.h
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_common_cmd_packet_util.py
  Examples/minimum_user/src/src_user/TlmCmd/command_definitions.c
  Examples/minimum_user/src/src_user/TlmCmd/command_definitions.h
  TlmCmd/common_cmd_packet_util.c
  TlmCmd/common_cmd_packet_util.h
Labels: enhancement, priority::high

#366 CCP Util に param generator を追加
  Applications/divided_cmd_utility.h
  Examples/minimum_user/src/src_user/Settings/Modes/Transitions/sequence_items.c
  Script/CI/check_coding_rule.py
  TlmCmd/common_cmd_packet_util.c
  TlmCmd/common_cmd_packet_util.h
Labels: enhancement, priority::high

#368 Remove unneeded CMake target_properties()
  common.cmake
Labels: invalid, tools, S2E

#370 Update version (v3.6.0)
  c2a_core_main.h
Labels: priority::high
