Repository ut-issl/c2a-core, pull requests merged in 2022-01, with the labels that each got.

#152 HEWでコンパイルできない問題に対応
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/event_logger_params.h
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py
  System/EventManager/event_logger.h
Labels: bug, priority::high

#153 Cmd DBのアップデート
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB.xlsm
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_BCT.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
Labels: priority::medium, tools

#133 OBCT, TMGRの改修
  CmdTlm/common_tlm_cmd_packet_util.h
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py
  System/TimeManager/obc_time.c
  System/TimeManager/obc_time.h
  System/TimeManager/time_manager.c
  System/TimeManager/time_manager.h
Labels: priority::high

#172 認証情報を環境変数から取得できるようにした
  Examples/minimum_user_for_s2e/src/src_user/Test/README.md
  Examples/minimum_user_for_s2e/src/src_user/Test/utils/wings_utils.py
Labels: priority::low, tools

#114 UTL_cmdの追加
  CmdTlm/common_tlm_cmd_packet.h
  CmdTlm/packet_handler.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/Ccsds/TCPacket.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/Ccsds/TCPacket.h
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/command_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/common_tlm_cmd_packet.c
  Examples/minimum_user_for_s2e/src/src_user/CmdTlm/telemetry_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/CmdTlm/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py
  System/TimeManager/time_manager.c
  System/TimeManager/time_manager.h
Labels: enhancement, priority::high, WINGS

#178 Add link to discussion in readme
  README.md
Labels: documentation, priority::medium

#185 ソースコードの文字コードをUTF-8にした後の様々な微修正
  .github/workflows/check_encoding.yml
  Docs/General/CodingRule.md
  Examples/minimum_user_for_s2e/Doxyfile
  Examples/minimum_user_for_s2e/src/src_user/Script/activate_sils_define.bat
  Examples/minimum_user_for_s2e/src/src_user/Script/deactivate_sils_define.bat
  Examples/minimum_user_for_s2e/src/src_user/Settings/build_settings.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/sils_define.h
  Examples/minimum_user_for_s2e/src/src_user/Test/utils/c2a_enum_utils.py
  Script/CI/check_coding_rule.json
  Script/CI/check_coding_rule.py
  Script/CI/check_encoding.json
  Script/CI/check_encoding.py
  common.cmake
Labels: documentation, enhancement, priority::high, tools, S2E

#186 ドキュメントのファイル名の修正
  Docs/Application/overview.md
  Docs/Core/tips.md
  Docs/Driver/overview.md
  Docs/General/coding_rule.md
  Docs/General/overview.md
  Docs/README.md
  Docs/Sils/s2e_integration.md
  Docs/Tips/parameter_settings.md
  Docs/Tools/overview.md
Labels: documentation, priority::high

#188 Revert "Disable reviewdog clang-tidy (github-check)"
  .github/workflows/build_as_c89.yml
Labels: priority::medium, tools

#180 GS ドライバーのinit に CCSDS config の初期化を追加
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Com/gs.c
Labels: priority::low

#189 文字コードがUTF-8になったことによる， `#pragma section` スクリプトの修正
  Examples/minimum_user_for_s2e/src/src_user/Script/AddSection/AddSection.pl
  Examples/minimum_user_for_s2e/src/src_user/Script/AddSection/settings.pl
  Script/AddSection/AddSection.pl
  Script/AddSection/settings.pl
Labels: priority::medium, tools

#187 UART_Configにファイルシステム向けの設定を追加
  IfWrapper/uart.h
Labels: priority::medium

#190 リリースとバージョニングについての整備
  Docs/General/release.md
  Docs/README.md
  README.md
  c2a_core_main.h
Labels: documentation, priority::medium, tools

#191 Pre Release (v3.5.0-beta.0): UTF-8 への変更に伴い，Tools に非互換アップデートが入ったことによる Pre Release
  Docs/General/release.md
  c2a_core_main.h
Labels: documentation, priority::medium, tools

#182 Pre Release (v3.5.0-beta.1): UTL cmd のテストを追加する
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py
  System/TimeManager/time_manager.c
  System/TimeManager/time_manager.h
  c2a_core_main.h
Labels: priority::medium, WINGS

#192 pythonのフォーマットチェックCIとリンタCIをいれる
  .flake8
  .github/workflows/python_check_format.yml
  .github/workflows/python_lint.yml
  Examples/minimum_user_for_s2e/src/src_user/Test/README.md
  Examples/minimum_user_for_s2e/src/src_user/Test/test/conftest.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/CmdTlm/test_command_analyze.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/AnomalyLogger/test_anomaly_logger.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/ModeManager/test_mode_manager.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TaskManager/test_task_dispatcher.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_obc_time.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/WatchdogTimer/test_watchdog_timer.py
  Examples/minimum_user_for_s2e/src/src_user/Test/utils/c2a_enum_utils.py
  Examples/minimum_user_for_s2e/src/src_user/Test/utils/wings_utils.py
  Script/CI/check_coding_rule.py
  Script/CI/check_encoding.py
  pyproject.toml
Labels: enhancement, priority::medium, tools

#194 ビルドCIを，すべてのPRで回すように設定
  .github/workflows/build_as_c89.yml
  .github/workflows/build_as_cxx.yml
Labels: priority::high, tools

#196 CCP_EXEC_STS を整数に
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_DCU.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_DCU.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  System/EventManager/event_handler.c
  System/TaskManager/task_dispatcher.c
  TlmCmd/common_tlm_cmd_packet.h
Labels: enhancement, priority::high

#193 ApplicationsとLibraryを必要な場合のみadd_subdirectoryする修正
  CMakeLists.txt
Labels: priority::medium, tools

#207 Move TCPacket to C2A Core
  CMakeLists.txt
  Drivers/Super/driver_super.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/Ccsds/tcpacket_params.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/common_tlm_cmd_packet_define.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/common_tlm_cmd_packet_params.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/Ccsds/TCSegment.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/Ccsds/m_pdu.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/common_tlm_cmd_packet.c
  System/TimeManager/time_manager.c
  TlmCmd/Ccsds/TCPacket.c
  TlmCmd/Ccsds/TCPacket.h
Labels: priority::high

#203 Add E501 to ignore list for flake8
  .flake8
Labels: priority::medium, tools

#215 コード規約チェックCIのエラー出力を関数化する
  Script/CI/check_coding_rule.py
Labels: priority::medium, tools

#209 CTCPをCCPとTCPに分離
  Applications/anomaly_handler.c
  Applications/divided_cmd_utility.c
  Applications/memory_dump.c
  Applications/telemetry_manager.c
  Applications/telemetry_manager.h
  CMakeLists.txt
  Docs/Core/communication.md
  Docs/README.md
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Com/gs_validate.c
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Com/gs_validate.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/Transitions/SequenceItems.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/Ccsds/apid_define.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/Ccsds/tcpacket_params.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/common_cmd_packet_define.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/common_tlm_cmd_packet_define.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/common_tlm_cmd_packet_params.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/common_tlm_packet_define.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/common_cmd_packet.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/common_tlm_cmd_packet.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/common_tlm_packet.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/user_packet_handler.c
  Script/CI/check_coding_rule.json
  Script/CI/check_coding_rule.py
  System/EventManager/event_handler.c
  System/EventManager/event_logger.c
  System/ModeManager/mode_manager.c
  System/TimeManager/time_manager.c
  TlmCmd/Ccsds/TCPacket.c
  TlmCmd/Ccsds/TCPacket.h
  TlmCmd/block_command_executor.c
  TlmCmd/block_command_loader.c
  TlmCmd/block_command_loader.h
  TlmCmd/block_command_table.c
  TlmCmd/command_analyze.c
  TlmCmd/common_cmd_packet.h
  TlmCmd/common_cmd_packet_util.c
  TlmCmd/common_cmd_packet_util.h
  TlmCmd/common_tlm_cmd_packet.h
  TlmCmd/common_tlm_packet.h
  TlmCmd/packet_handler.c
  TlmCmd/telemetry_generator.c
Labels: documentation, enhancement, priority::high

#216 check_coding_ruleの出力をreviewdogから出す
  .github/workflows/check_coding_rule.yml
Labels: priority::medium, tools

#212 PacketList で使える packet の型を任意にする
  Applications/timeline_command_dispatcher.c
  CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/Ccsds/tcp_to_m_pdu.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/telemetry_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/user_packet_handler.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/user_packet_handler.h
  Script/CI/check_coding_rule.json
  System/TaskManager/task_dispatcher.c
  System/TaskManager/task_dispatcher.h
  TlmCmd/command_dispatcher.c
  TlmCmd/packet_handler.c
  TlmCmd/packet_handler.h
  TlmCmd/packet_list.c
  TlmCmd/packet_list.h
  TlmCmd/packet_list_util.c
  TlmCmd/packet_list_util.h
Labels: enhancement, priority::high

#224 Remove duplicate error on reviewdog
  .github/workflows/build_as_c89.yml
  Script/CI/remove_duplicate_error.py
Labels: priority::high, tools

#221 Fix bce command prefix
  Docs/Tips/parameter_settings.md
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user_for_s2e/src/src_user/Test/test/conftest.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/ModeManager/test_mode_manager.py
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.h
  TlmCmd/block_command_executor.c
  TlmCmd/block_command_executor.h
  TlmCmd/block_command_loader.c
  TlmCmd/block_command_table.c
  TlmCmd/block_command_table.h
Labels: good first issue, priority::medium

#208 TIとunixtimeの変換精度を向上させる補正機能の追加
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/telemetry_definitions.c
  System/TimeManager/obc_time.c
  System/TimeManager/obc_time.h
  System/TimeManager/time_manager.c
  System/TimeManager/time_manager.h
Labels: enhancement, priority::medium
