Repository ut-issl/c2a-core, pull requests merged in 2022-10, with the labels that each got.

#444 Pre Release (v3.8.0-beta.1): エンディアン関連の関数の整理
  Applications/anomaly_handler.c
  Applications/memory_dump.c
  Applications/telemetry_manager.c
  Docs/General/coding_rule.md
  Drivers/Protocol/common_tlm_cmd_packet_for_driver_super.c
  Drivers/Protocol/eb90_frame_for_driver_super.c
  Drivers/Protocol/eb90_packet_for_driver_super.c
  Drivers/Super/driver_super.h
  Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.c
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_gs.c
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc_telemetry_buffer.c
  Examples/minimum_user/src/src_user/Drivers/Etc/uart_test.c
  Examples/minimum_user/src/src_user/Settings/Modes/Transitions/sequence_items.c
  Library/CMakeLists.txt
  Library/endian.c
  Library/endian.h
  Library/endian_conv.c
  Library/endian_conv.h
  Library/endian_memcpy.c
  Library/endian_memcpy.h
  System/AnomalyLogger/anomaly_logger.c
  System/ApplicationManager/app_manager.c
  System/ModeManager/mode_manager.c
  TlmCmd/Ccsds/cmd_space_packet.c
  TlmCmd/Ccsds/space_packet.c
  TlmCmd/block_command_executor.c
  TlmCmd/block_command_loader.c
  TlmCmd/block_command_table.c
  TlmCmd/common_cmd_packet_util.c
  TlmCmd/telemetry_frame.c
  c2a_core_main.h
Labels: enhancement, priority::high, tools

#445 DS のフレーム長取得にパケット内部のエンディアンを考慮
  Drivers/Super/driver_super.c
  Drivers/Super/driver_super.h
Labels: enhancement, priority::high

#439 CCITT Right の CRC を有効化
  Library/crc.c
  Library/crc.h
Labels: priority::high

#450 UART TLM ON OFF を追加
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_gs.c
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_gs.h
  Examples/minimum_user/src/src_user/Drivers/Com/gs.c
  Examples/minimum_user/src/src_user/Drivers/Com/gs.h
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user/src/src_user/TlmCmd/command_definitions.c
  Examples/minimum_user/src/src_user/TlmCmd/command_definitions.h
  Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.c
Labels: enhancement, priority::low

#459 MOBC経由でのパケット配送時に，2nd OBC での Cmd 実行種別のバグを修正
  Docs/Core/communication.md
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.h
  Examples/minimum_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.h
  TlmCmd/packet_handler.c
Labels: bug, priority::high
