Repository ut-issl/c2a-core, pull requests merged in 2022-03, with the labels that each got.

#262 ELのデバッグ出力を追加
  Examples/minimum_user_for_s2e/src/src_user/Applications/UserDefined/debug_apps.c
  Examples/minimum_user_for_s2e/src/src_user/Applications/UserDefined/debug_apps.h
  Examples/minimum_user_for_s2e/src/src_user/Applications/app_registry.c
  Examples/minimum_user_for_s2e/src/src_user/Applications/app_registry.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/TaskLists/Elements/tl_elem_debug_display.c
Labels: priority::medium

#253 BCLの double, uint64, int64 型引数を有効化して検証する
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_BCT.csv
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/CmdTlm/test_block_command_loader.py
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_header.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_test_bcl.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/block_command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/block_command_definitions.h
  TlmCmd/block_command_loader.c
  TlmCmd/block_command_loader.h
Labels: enhancement, priority::high

#263 C2A Coreの搭載実績を書く
  README.md
Labels: documentation, priority::medium

#269 Readmeの注釈をGFMの新機能にする
  README.md
Labels: documentation, priority::medium

#272 Renovate の設定を更新
  renovate.json
Labels: priority::medium, tools

#279 CIが通らない問題を解決
  .github/workflows/build_as_c89.yml
Labels: bug, priority::high

#277 GS の受信時刻の修正
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Com/gs.c
Labels: priority::low

#278 ELデバッグ出力を短く
  Examples/minimum_user_for_s2e/src/src_user/Applications/UserDefined/debug_apps.c
Labels: priority::low

#276 UTL_cmdのpytestの修正
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py
Labels: bug, priority::high

#280 Pythonスクリプトの返り値を整理
  Script/CI/check_coding_rule.py
  Script/CI/check_encoding.py
Labels: priority::low, tools

#264 DRのないOBCで，不要なメモリを確保しないようにする
  Examples/minimum_user_for_s2e/src/src_user/Settings/Applications/data_recorder_define.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/packet_handler_params.h
  TlmCmd/packet_handler.c
  TlmCmd/packet_handler.h
Labels: priority::medium

#281 PH の返り値を元に戻す
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/user_packet_handler.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/user_packet_handler.h
  TlmCmd/packet_handler.c
  TlmCmd/packet_handler.h
Labels: priority::medium

#284 PHの返り値修正に伴う，tlm dbの更新
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
Labels: priority::medium

#289 TFとCAの初期化コマンドを追加
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.h
  TlmCmd/command_analyze.c
  TlmCmd/command_analyze.h
  TlmCmd/telemetry_frame.c
  TlmCmd/telemetry_frame.h
Labels: priority::high

#286 EHの設定のdefineの位置が不適切なのを直した
  System/EventManager/event_handler.h
Labels: bug, priority::high

#290 AL，AHはdeprecatedなので，簡単に無効化できるようにした
  Applications/anomaly_handler.c
  Applications/anomaly_handler.h
  Applications/utility_counter.c
  Applications/utility_counter.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/AnomalyLogger/al_default_settings.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/Transitions/sequence_items.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/anomaly_logger_define.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/anomaly_logger_group.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/anomaly_logger_settings.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/anomaly_logger_settings.h
  System/AnomalyLogger/anomaly_logger.c
  System/AnomalyLogger/anomaly_logger.h
  c2a_core_main.c
Labels: priority::medium

#293 ALはdeprecatedなので，cmakelistsから外す
  CMakeLists.txt
  Examples/minimum_user_for_s2e/CMakeLists.txt
Labels: priority::high

#291 pytest confest で EL_CORE_GROUP_TLCD_DEPLOY_BLOCK EL が出るのを防ぐ
  Examples/minimum_user_for_s2e/src/src_user/Test/test/conftest.py
Labels: bug, priority::high

#288 Pre Release (v3.6.0-beta.0): TLM生成関数の返り値を int から TF_ACK にするなど
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc_telemetry_buffer.c
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc_telemetry_buffer.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TF.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_TF.csv
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/CmdTlm/test_telemetry_frame.py
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/telemetry_definitions.c
  TlmCmd/telemetry_frame.c
  TlmCmd/telemetry_frame.h
  TlmCmd/telemetry_generator.c
  c2a_core_main.h
Labels: priority::medium, tools

#295 pytestでCmdTlmというディレクトリが残っていたので修正
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/TlmCmd/test_block_command_loader.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/TlmCmd/test_command_analyze.py
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/TlmCmd/test_telemetry_frame.py
Labels: priority::medium

#297 EL noteのテレメをu32に
  Examples/minimum_user_for_s2e/src/src_user/Settings/System/event_logger_params.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL_CLOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL_TLOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EL_CLOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EL_TLOG.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/telemetry_definitions.c
  System/EventManager/event_logger.h
Labels: priority::medium

#287 Command パケット周辺の簡易リファクタリング
  Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_gs.c
  Examples/minimum_user_for_s2e/src/src_user/Applications/DriverInstances/di_gs.h
  Examples/minimum_user_for_s2e/src/src_user/Applications/UserDefined/debug_apps.c
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc_telemetry_buffer.c
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Aocs/aobc_telemetry_data_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Com/gs.c
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Com/gs.h
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Com/gs_validate.c
  Examples/minimum_user_for_s2e/src/src_user/Drivers/Com/gs_validate.h
  Examples/minimum_user_for_s2e/src/src_user/IfWrapper/Sils/ccsds_sils.cpp
  Examples/minimum_user_for_s2e/src/src_user/IfWrapper/ccsds_user.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBaseAobc/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/Ccsds/TCFrame.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/Ccsds/TCFrame.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/Ccsds/TCSegment.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/Ccsds/TCSegment.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/Ccsds/tc_segment.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/Ccsds/tc_segment.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/Ccsds/tc_transfer_frame.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/Ccsds/tc_transfer_frame.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.h
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/telemetry_definitions.c
Labels: priority::high

#302 EHのrule初期化，再有効化時の処理を修正
  Examples/minimum_user_for_s2e/src/src_user/Applications/UserDefined/debug_apps.c
  Examples/minimum_user_for_s2e/src/src_user/Applications/UserDefined/debug_apps.h
  Examples/minimum_user_for_s2e/src/src_user/Applications/app_registry.c
  Examples/minimum_user_for_s2e/src/src_user/Applications/app_registry.h
  Examples/minimum_user_for_s2e/src/src_user/Settings/Modes/TaskLists/Elements/tl_elem_debug_display.c
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.c
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/command_definitions.h
  System/EventManager/event_handler.c
  System/EventManager/event_handler.h
Labels: priority::high
