Repository ut-issl/c2a-core, pull requests merged in 2022-05, with the labels that each got.

#325 HKで表示するTL_IDが間違っているテレメがあったので修正
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/telemetry_definitions.c
Labels: priority::medium

#324 s2e-core更新に伴うCmake関連ファイルの修正
  .github/workflows/build_with_s2e.yml
  common.cmake
Labels: priority::high, S2E

#327 telemetry_definition.c でAOBCの設定を消してしまっていたので、直す
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/telemetry_definitions.c
Labels: priority::high

#326 Pre Release (v3.6.0-beta.4): WINGS側でUTLが0.1s精度で打てるようになったことへの対応
  Examples/minimum_user_for_s2e/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py
  System/TimeManager/time_manager.c
  System/TimeManager/time_manager.h
  c2a_core_main.h
Labels: priority::medium, WINGS

#329 Fix CMake option default value config
  Examples/minimum_user_for_s2e/CMakeLists.txt
Labels: bug, priority::high, tools, S2E

#330 Fix libC2A build
  .github/workflows/build_as_c89.yml
  .github/workflows/build_as_cxx.yml
  .github/workflows/build_with_s2e.yml
  CMakeLists.txt
Labels: bug, priority::high, tools, S2E

#332 TSP周りのflagsの綴りを修正
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/common_tlm_packet.c
  TlmCmd/Ccsds/tlm_space_packet.c
  TlmCmd/Ccsds/tlm_space_packet.h
  TlmCmd/telemetry_generator.c
Labels: priority::low

#328 tlmを簡素に
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_AM.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_BL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_CA.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_AM.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_BL.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_CA.csv
  Examples/minimum_user_for_s2e/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_TL.csv
  Examples/minimum_user_for_s2e/src/src_user/TlmCmd/telemetry_definitions.c
Labels: priority::medium

#333 SPIヘッダをC89に対応
  IfWrapper/spi.h
Labels: bug, priority::high

#336 Ignore example user's main() on SILS environment
  Examples/minimum_user_for_s2e/CMakeLists.txt
  Examples/minimum_user_for_s2e/src/src_user/c2a_main.c
Labels: invalid, priority::medium, S2E
