Repository ut-issl/c2a-core, pull requests merged in 2023-02, with the labels that each got.

#488 Fix typo "Tlemetry"
  Docs/Core/communication.md
Labels: documentation

#494 Use fixed version python tools
  .github/workflows/python_check_format.yml
  .github/workflows/python_lint.yml
Labels: priority::high, tools

#492 Update black to 23.1.0 from 22.12.0
  .github/workflows/python_check_format.yml
  Examples/2nd_obc_user/src/src_user/Test/test/conftest.py
  Examples/minimum_user/src/src_user/Test/test/conftest.py
  Examples/minimum_user/src/src_user/Test/test/src_core/Applications/test_timeline_command_dispatcher.py
  Examples/minimum_user/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py
  Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_block_command_loader.py
Labels: priority::high, tools

#490 テレメ生成時のAPID判定のバグ修正
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.c
  Examples/minimum_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.c
Labels: bug, priority::high

#493 Pre Release (v3.8.0-beta.4): 認証なしの最新の WINGS への対応
  .gitignore
  Examples/2nd_obc_user/src/src_user/Test/authorization.json.temp
  Examples/2nd_obc_user/src/src_user/Test/utils/wings_utils.py
  Examples/2nd_obc_user/sync_with_minimum_user.bat
  Examples/minimum_user/src/src_user/Test/README.md
  Examples/minimum_user/src/src_user/Test/authorization.json.temp
  Examples/minimum_user/src/src_user/Test/utils/wings_utils.py
  c2a_core_main.h
Labels: priority::high, tools

#497 最新の Tlm Cmd DB へ更新
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_AOBC_CMD_DB.xlsm
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_AOBC_TLM_DB.xlsm
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB.xlsm
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB.xlsm
Labels: priority::high, tools

#486 I2Cのread/write関数追加
  CMakeLists.txt
  Examples/2nd_obc_user/src/src_user/IfWrapper/CMakeLists.txt
  Examples/2nd_obc_user/src/src_user/IfWrapper/Sils/i2c_sils.cpp
  Examples/2nd_obc_user/src/src_user/IfWrapper/SilsMockup/i2c_sils.c
  Examples/minimum_user/src/src_user/IfWrapper/CMakeLists.txt
  Examples/minimum_user/src/src_user/IfWrapper/Sils/i2c_sils.cpp
  Examples/minimum_user/src/src_user/IfWrapper/SilsMockup/i2c_sils.c
  IfWrapper/Common/i2c_common.c
  IfWrapper/Common/i2c_common.h
  IfWrapper/i2c.h
Labels: priority::high

#498 OPTIMAL-1 を実績リストに修正 & 実績リストの微修正
  README.md
Labels: documentation, priority::medium
