Repository ut-issl/c2a-core, pull requests merged in 2023-05, with the labels that each got.

#559 コーディング規約に利用可能な略語リスト（初版）を追加
  Docs/General/coding_acronyms.md
  Docs/General/coding_rule.md
  Docs/README.md
Labels: documentation, priority::medium

#564 Pre Release (v3.9.0-beta.3): Packaging as Rust crate
  .gitignore
  Cargo.toml
  Docs/General/release.md
  c2a_core_main.h
  src/lib.rs
Labels: enhancement, priority::high

#563 packet list の変数名が pli と pl で表記ゆれしていたのを pl に統一する
  TlmCmd/packet_list.c
Labels: priority::medium

#562 Tlm の Destination Flags で，複数配送先のパケットをそれぞれの配送先に送るときに，flag をその配送先のみにする
  Docs/Core/communication.md
  TlmCmd/packet_handler.c
Labels: documentation, priority::medium

#566 Fix crate package license config
  Cargo.toml
Labels: enhancement, priority::medium

#567 Change c2a-core crate to no_std
  src/lib.rs
Labels: enhancement, priority::medium

#568 Add export src interface (c2a-core crate)
  Cargo.toml
  src/lib.rs
Labels: enhancement, priority::high, tools

#561 Pre Release (v3.9.0-beta.4): CCP_DEST_TYPE_TO_APID を追加し，コマンドのルーティングを見直す
  Docs/Core/communication.md
  Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.c
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.c
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.h
  Examples/2nd_obc_user/src/src_user/TlmCmd/user_packet_handler.c
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_aobc.c
  Examples/minimum_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.c
  Examples/minimum_user/src/src_user/Settings/TlmCmd/common_cmd_packet_define.h
  Examples/minimum_user/src/src_user/TlmCmd/user_packet_handler.c
  TlmCmd/common_cmd_packet.h
  TlmCmd/packet_handler.c
  c2a_core_main.h
Labels: documentation, priority::high

#569 Pre Release (v3.9.0-beta.4): バージョンアップのやり直し
  Cargo.toml
Labels: bug, priority::high

#572 Pre Release (v3.9.0-beta.5): tlm-cmd-code-generator の更新
  Cargo.toml
  Examples/2nd_obc_user/src/src_user/TlmCmd/command_definitions.c
  Examples/2nd_obc_user/src/src_user/TlmCmd/telemetry_definitions.c
  Examples/minimum_user/src/src_user/TlmCmd/command_definitions.c
  Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.c
  c2a_core_main.h
Labels: priority::high, tools

#574 Remove duplicate Rust crate package license config
  Cargo.toml
Labels: priority::high, tools

#573 Check c2a-core version header in Rust build script
  Cargo.toml
  build.rs
Labels: enhancement, priority::medium, tools

#575 Add rust ci
  .github/workflows/rust.yml
Labels: priority::high, tools

#82 Pre Release (v3.9.0-beta.6): git_revision.cをどうにかする
  CMakeLists.txt
  Cargo.toml
  Examples/2nd_obc_user/CMakeLists.txt
  Examples/2nd_obc_user/src/src_user/Applications/UserDefined/debug_apps.c
  Examples/2nd_obc_user/src/src_user/Library/CMakeLists.txt
  Examples/2nd_obc_user/src/src_user/Library/git_revision.c
  Examples/2nd_obc_user/src/src_user/Library/git_revision.h
  Examples/2nd_obc_user/src/src_user/Script/Git/revision.bat
  Examples/2nd_obc_user/src/src_user/Script/Git/revision.sh
  Examples/2nd_obc_user/src/src_user/Script/git_revision.bat
  Examples/2nd_obc_user/src/src_user/Script/git_revision.sh
  Examples/2nd_obc_user/src/src_user/Script/git_revision.tmp
  Examples/2nd_obc_user/src/src_user/Settings/git_revision_config.h
  Examples/2nd_obc_user/src/src_user/TlmCmd/telemetry_source.h
  Examples/2nd_obc_user/src/src_user/c2a_main.c
  Examples/2nd_obc_user/sync_with_minimum_user.bat
  Examples/minimum_user/CMakeLists.txt
  Examples/minimum_user/src/src_user/Applications/UserDefined/debug_apps.c
  Examples/minimum_user/src/src_user/Library/CMakeLists.txt
  Examples/minimum_user/src/src_user/Library/git_revision.c
  Examples/minimum_user/src/src_user/Library/git_revision.h
  Examples/minimum_user/src/src_user/Script/Git/revision.bat
  Examples/minimum_user/src/src_user/Script/Git/revision.sh
  Examples/minimum_user/src/src_user/Script/git_revision.bat
  Examples/minimum_user/src/src_user/Script/git_revision.sh
  Examples/minimum_user/src/src_user/Script/git_revision.tmp
  Examples/minimum_user/src/src_user/Settings/git_revision_config.h
  Examples/minimum_user/src/src_user/TlmCmd/telemetry_source.h
  Examples/minimum_user/src/src_user/c2a_main.c
  Library/git_revision.h
  Script/Git/revision.bat
  Script/Git/revision.sh
  Script/GitHooks/pre-commit
  c2a_core_main.c
  c2a_core_main.h
Labels: priority::medium, tools

#583 Split obc time config header
  System/TaskManager/task_dispatcher.c
  System/TimeManager/obc_time.c
  System/TimeManager/obc_time.h
  System/TimeManager/obc_time_config.h
  System/TimeManager/time_manager.c
Labels: priority::medium

#584 古い `GENERATE_TLM` の利用を消す（telemetry manager , pytest 以外）
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/CMDFILE/sample.ops
  Examples/2nd_obc_user/src/src_user/Test/test/conftest.py
  Examples/2nd_obc_user/src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_start_hk_tlm.c
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMDFILE/sample.ops
  Examples/minimum_user/src/src_user/Test/test/conftest.py
  Examples/minimum_user/src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_start_hk_tlm.c
Labels: priority::high

#579 Add clang runtime feature
  .github/workflows/rust.yml
  Cargo.toml
Labels: enhancement, tools

#580 Export src dir via cargo
  Cargo.toml
  build.rs
Labels: enhancement, priority::high, tools

#578 Remove set-output
  .github/workflows/check_coding_rule.yml
Labels: priority::high, tools

#588 Pre Release (v3.9.0-beta.7): pytest 内の古い `GENERATE_TLM` の利用を消す
  Cargo.toml
  Examples/2nd_obc_user/src/src_user/Test/test/test_comm_between_c2a.py
  Examples/minimum_user/src/src_user/Test/test/src_core/Applications/test_event_utility.py
  Examples/minimum_user/src/src_user/Test/test/src_core/Applications/test_timeline_command_dispatcher.py
  Examples/minimum_user/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py
  Examples/minimum_user/src/src_user/Test/test/src_core/System/EventManager/test_event_logger.py
  Examples/minimum_user/src/src_user/Test/test/src_core/System/ModeManager/test_mode_manager.py
  Examples/minimum_user/src/src_user/Test/test/src_core/System/TimeManager/test_time_manager.py
  Examples/minimum_user/src/src_user/Test/test/src_core/System/WatchdogTimer/test_watchdog_timer.py
  Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_block_command_loader.py
  Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_command_analyze.py
  Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_command_dispatcher.py
  Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_common_cmd_packet_util.py
  Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_telemetry_frame.py
  c2a_core_main.h
Labels: priority::high, tools, WINGS

#593 CCP_form_and_exec_rtc_to_other_obc を追加する
  TlmCmd/common_cmd_packet_util.c
  TlmCmd/common_cmd_packet_util.h
Labels: priority::medium

#600 Pre Release (v3.9.0-beta.8): Fix get c2a-core git revision working dir
  CMakeLists.txt
  Cargo.toml
  Examples/2nd_obc_user/CMakeLists.txt
  Examples/minimum_user/CMakeLists.txt
  c2a_core_main.h
Labels: bug, priority::high, tools, S2E
