Repository ut-issl/c2a-core, pull requests merged in 2023-03, with the labels that each got.

#501 DS buffer のバグ修正（可変フレーム，フレーム長なし，フッタあり）
  Drivers/Super/driver_super.c
Labels: bug, priority::high

#502 DS のコメントスタイルを修正
  Drivers/Super/driver_super.c
  Drivers/Super/driver_super.h
Labels: priority::medium

#510 実績リストに SPHERE-1 EYE を追加
  README.md
Labels: documentation, priority::low

#509 タイポ修正
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.h
Labels: priority::low

#503 DS での rx_buffer を stream ごとに driver instance から設定可能にする
  Drivers/Super/driver_super.c
  Drivers/Super/driver_super.h
  Examples/2nd_obc_user/src/src_user/Applications/DriverInstances/di_mobc.c
  Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.c
  Examples/2nd_obc_user/src/src_user/Drivers/Etc/mobc.h
  Examples/2nd_obc_user/src/src_user/Settings/DriverSuper/driver_buffer_define.h
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_aobc.c
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_gs.c
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_uart_test.c
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_uart_test.h
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.h
  Examples/minimum_user/src/src_user/Drivers/Com/gs.c
  Examples/minimum_user/src/src_user/Drivers/Com/gs.h
  Examples/minimum_user/src/src_user/Drivers/Etc/uart_test.c
  Examples/minimum_user/src/src_user/Drivers/Etc/uart_test.h
  Examples/minimum_user/src/src_user/Settings/DriverSuper/driver_buffer_define.h
Labels: enhancement, priority::high

#505 uart_test_instance のリネーム
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_uart_test.c
  Examples/minimum_user/src/src_user/Applications/DriverInstances/di_uart_test.h
  Examples/minimum_user/src/src_user/Drivers/Etc/uart_test.c
  Examples/minimum_user/src/src_user/Drivers/Etc/uart_test.h
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_UART_TEST.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_UART_TEST.csv
  Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.c
Labels: priority::medium

#506 DS_IF_RX_BUFFER_SIZE の可変長化
  Drivers/Super/driver_super.c
  Drivers/Super/driver_super.h
Labels: enhancement, priority::high

#507 DS の関数の順序を微修正
  Drivers/Super/driver_super.c
  Drivers/Super/driver_super.h
Labels: priority::medium

#508 Pre Release (v3.8.0-beta.5): DS に受信フレームの最大値の設定を追加
  Drivers/Protocol/common_tlm_cmd_packet_for_driver_super.c
  Drivers/Super/driver_super.c
  Drivers/Super/driver_super.h
  c2a_core_main.h
Labels: enhancement, priority::medium

#520 Fix USE_SIMPLE_LIBC option definition to top
  CMakeLists.txt
  Library/CMakeLists.txt
Labels: bug, tools

#518 Use arkedge/workflows-c2a/c2a-build.yml for Build CI
  .github/workflows/build.yml
  .github/workflows/build_as_c89.yml
  .github/workflows/build_as_cxx.yml
Labels: enhancement, tools

#515 Pre Release (v3.8.0-beta.7): Tlm Space Packet の 2nd header の DESTINATION INFO のフィールド名変更
  Docs/Core/communication.md
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc_telemetry_buffer.c
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc_telemetry_data_definitions.h
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_AM.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_APP_TIME.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_BL.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_CA.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_DCU.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_INDEX.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_LOG.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EH_RULE.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL_CLOG.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_EL_TLOG.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_GIT_REV.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MEM.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MM.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TF.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TL.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_TLM_MGR.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_UART_TEST.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_AM.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_APP_TIME.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_BL.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_CA.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_DCU.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH_INDEX.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH_LOG.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EH_RULE.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EL.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EL_CLOG.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_EL_TLOG.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_GIT_REV.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_GS.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MEM.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MM.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_TF.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_TL.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_TLM_MGR.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_UART_TEST.csv
  TlmCmd/Ccsds/tlm_space_packet.c
  TlmCmd/Ccsds/tlm_space_packet.h
  TlmCmd/telemetry_generator.c
  c2a_core_main.h
Labels: documentation, priority::high

#516 Anomaly Logger, Anomaly Handler の完全削除
  Applications/CMakeLists.txt
  Applications/anomaly_handler.c
  Applications/anomaly_handler.h
  Applications/timeline_command_dispatcher.c
  Applications/utility_counter.c
  Applications/utility_counter.h
  CMakeLists.txt
  Docs/Tips/parameter_settings.md
  Examples/2nd_obc_user/src/src_user/Settings/System/EventHandlerRules/event_handler_rules.h
  Examples/2nd_obc_user/src/src_user/Settings/System/anomaly_logger_define.h
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_AOBC_CMD_DB_BCT.csv
  Examples/2nd_obc_user/src/src_user/TlmCmd/block_command_definitions.h
  Examples/minimum_user/CMakeLists.txt
  Examples/minimum_user/src/src_user/Applications/UserDefined/debug_apps.c
  Examples/minimum_user/src/src_user/Applications/app_headers.h
  Examples/minimum_user/src/src_user/Applications/app_registry.c
  Examples/minimum_user/src/src_user/Applications/app_registry.h
  Examples/minimum_user/src/src_user/Settings/Applications/AnomalyHandlerRules/ah_rules.h
  Examples/minimum_user/src/src_user/Settings/Applications/AnomalyHandlerRules/ahr_default_load.c
  Examples/minimum_user/src/src_user/Settings/Applications/anomaly_handler_params.h
  Examples/minimum_user/src/src_user/Settings/CMakeLists.txt
  Examples/minimum_user/src/src_user/Settings/Modes/TaskLists/tl_initial.c
  Examples/minimum_user/src/src_user/Settings/Modes/Transitions/sequence_items.c
  Examples/minimum_user/src/src_user/Settings/System/EventHandlerRules/event_handler_rules.h
  Examples/minimum_user/src/src_user/Settings/System/anomaly_logger_define.h
  Examples/minimum_user/src/src_user/Settings/System/anomaly_logger_group.h
  Examples/minimum_user/src/src_user/Settings/System/anomaly_logger_params.h
  Examples/minimum_user/src/src_user/Settings/System/anomaly_logger_settings.c
  Examples/minimum_user/src/src_user/Settings/System/anomaly_logger_settings.h
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_BCT.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user/src/src_user/Test/test/src_core/System/AnomalyLogger/test_anomaly_logger.py
  Examples/minimum_user/src/src_user/TlmCmd/block_command_definitions.h
  Examples/minimum_user/src/src_user/TlmCmd/command_definitions.c
  Examples/minimum_user/src/src_user/TlmCmd/command_definitions.h
  Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.c
  System/AnomalyLogger/anomaly_logger.c
  System/AnomalyLogger/anomaly_logger.h
  System/ApplicationManager/app_manager.c
  System/EventManager/event_logger.h
  System/ModeManager/mode_manager.c
  System/TaskManager/task_dispatcher.c
  TlmCmd/block_command_executor.h
  TlmCmd/block_command_table.h
  c2a_core_main.c
Labels: documentation, enhancement, priority::high

#524 Update version (v3.8.0)
  c2a_core_main.h
Labels: priority::high
