Repository ut-issl/c2a-core, pull requests merged in 2023-04, with the labels that each got.

#499 CDISの実行エラーのEL登録のlocal id を cmd id にした
  Examples/minimum_user/src/src_user/Test/test/src_core/TlmCmd/test_command_dispatcher.py
  TlmCmd/command_dispatcher.c
  TlmCmd/command_dispatcher.h
Labels: priority::medium

#500 BC展開時刻被りはコマンド実行エラーにしないようにした
  Applications/timeline_command_dispatcher.c
Labels: priority::medium

#530 PH_ACK のコメントを微修正
  TlmCmd/packet_handler.h
Labels: priority::low

#534 S2E Build CI で使われる S2E Core のバージョンを上げる
  .github/workflows/build_with_s2e.yml
Labels: priority::high, tools

#533 BC_AR_GS_RELATED_PROCESS を combine にして，Cmd受付処理の頻度をあげる (2nd OBC)
  Examples/2nd_obc_user/src/src_user/Settings/Modes/TaskLists/tl_initial.c
Labels: priority::medium

#529 Pre Release (v3.9.0-beta.0): Cmd DB から "Cmd_" prefix を削除
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_AOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  c2a_core_main.h
Labels: priority::high, tools

#535 APID_is_other_obc_tlm_apid の削除
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.c
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.h
  Examples/minimum_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.c
  Examples/minimum_user/src/src_user/Settings/TlmCmd/Ccsds/apid_define.h
  TlmCmd/telemetry_generator.c
Labels: priority::high

#541 自身のOBCのテレメを生成する `Cmd_TG_GENERATE_TLM` と便利エイリアスの実装
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_AOBC_CMD_DB_CMD_DB.csv
  Examples/2nd_obc_user/src/src_user/TlmCmd/command_definitions.c
  Examples/2nd_obc_user/src/src_user/TlmCmd/command_definitions.h
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc_command_definitions.h
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user/src/src_user/TlmCmd/command_definitions.c
  Examples/minimum_user/src/src_user/TlmCmd/command_definitions.h
  TlmCmd/Ccsds/tlm_space_packet.c
  TlmCmd/Ccsds/tlm_space_packet.h
  TlmCmd/telemetry_generator.c
  TlmCmd/telemetry_generator.h
Labels: enhancement, priority::high

#544 Pre Release (v3.9.0-beta.1): Cmd_TG_FORWARD_TLM の実装
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_AOBC_CMD_DB_CMD_DB.csv
  Examples/2nd_obc_user/src/src_user/Test/test/test_comm_between_c2a.py
  Examples/2nd_obc_user/src/src_user/TlmCmd/command_definitions.c
  Examples/2nd_obc_user/src/src_user/TlmCmd/command_definitions.h
  Examples/2nd_obc_user/src/src_user/TlmCmd/user_packet_handler.c
  Examples/2nd_obc_user/src/src_user/TlmCmd/user_packet_handler.h
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc_command_definitions.h
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user/src/src_user/TlmCmd/command_definitions.c
  Examples/minimum_user/src/src_user/TlmCmd/command_definitions.h
  Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.c
  Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.h
  Examples/minimum_user/src/src_user/TlmCmd/user_packet_handler.c
  Examples/minimum_user/src/src_user/TlmCmd/user_packet_handler.h
  TlmCmd/telemetry_generator.c
  TlmCmd/telemetry_generator.h
  c2a_core_main.h
Labels: enhancement, priority::high, tools

#532 Refactor example user IfWrapper CMake
  Examples/2nd_obc_user/src/src_user/IfWrapper/CMakeLists.txt
  Examples/minimum_user/src/src_user/IfWrapper/CMakeLists.txt
Labels: tools

#555 EL の doxygen コメントの軽微な修正
  System/EventManager/event_logger.h
Labels: documentation, priority::medium

#527 Pre Release (v3.9.0-beta.2): Split C89 compile option to BUILD_C2A_AS_C99
  CMakeLists.txt
  c2a_core_main.h
  common.cmake
Labels: priority::high, tools
