Repository ut-issl/c2a-core, pull requests merged in 2023-06, with the labels that each got.

#602 Update version (v3.9.0)
  Cargo.toml
  c2a_core_main.h
Labels: priority::high

#606 不要な空行を削除 などの軽微な修正
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
Labels: priority::low

#604 Fix build.rs by clippy
  build.rs
Labels: invalid, priority::high, tools

#605 Update new git_revision docs
  Examples/minimum_user/src/src_user/Settings/git_revision_config.h
Labels: documentation, tools

#607 Remove unused -rdynamic link option
  common.cmake
Labels: bug, priority::high, tools

#608 task dispatcher のタイポを修正
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/2nd_obc_user/src/src_user/TlmCmd/telemetry_definitions.c
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.c
  System/TaskManager/task_dispatcher.c
  System/TaskManager/task_dispatcher.h
Labels: priority::low

#609 コマンドの注釈を微修正
  Applications/telemetry_manager.h
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
Labels: documentation

#610 EH の pytest が特定環境で通らないことの修正
  Examples/minimum_user/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py
Labels: bug

#611 Update version (v3.9.1)
  Cargo.toml
  c2a_core_main.h
Labels: priority::high

#612 Update main (v3.9.1) on 2023-06-13
  .github/workflows/build.yml
  .github/workflows/rust.yml
  Applications/telemetry_manager.h
  Cargo.toml
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_AOBC.csv
  Examples/2nd_obc_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_AOBC_TLM_DB_AOBC_HK.csv
  Examples/2nd_obc_user/src/src_user/TlmCmd/telemetry_definitions.c
  Examples/minimum_user/src/src_user/Drivers/Aocs/aobc.c
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/CMD_DB/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_HK.csv
  Examples/minimum_user/src/src_user/Settings/TlmCmd/DataBase/TLM_DB/calced_data/SAMPLE_MOBC_TLM_DB_MOBC.csv
  Examples/minimum_user/src/src_user/Settings/git_revision_config.h
  Examples/minimum_user/src/src_user/Test/test/src_core/System/EventManager/test_event_handler.py
  Examples/minimum_user/src/src_user/TlmCmd/telemetry_definitions.c
  System/TaskManager/task_dispatcher.c
  System/TaskManager/task_dispatcher.h
  build.rs
  c2a_core_main.h
  common.cmake
Labels: priority::high

#614 異なる型の enum を比較している箇所を修正する
  TlmCmd/common_cmd_packet_util.c
Labels: bug, priority::high

#617 endian.c の include の修正
  Library/endian.c
Labels: bug, priority::high

#624 Ignore pragma section REPRO warning on MSVC
  common.cmake
Labels: priority::low, tools, S2E

#622 Fix function prototype mismatch in Applications
  Applications/event_utility.c
  Applications/nop.c
Labels: priority::medium

#625 Update version (v3.9.2)
  Cargo.toml
  c2a_core_main.h
Labels: priority::medium

#627 Update main (v3.9.2) on 2023-06-29
  .github/workflows/build.yml
  .github/workflows/check_coding_rule.yml
  Applications/event_utility.c
  Applications/nop.c
  Cargo.toml
  Library/endian.c
  TlmCmd/common_cmd_packet_util.c
  c2a_core_main.h
  common.cmake
Labels: priority::medium
